name: supaeromoon_ground_station
description: "The Ground Station app for the Supaeromoon rover."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  ffi: ^2.1.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  google_fonts: ^6.3.2
  latext: ^0.5.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/sound_library/
